services:
  web:
    container_name: nginx-port
    build: ./nginx-port
    ports:
      - '8095:8050'
    volumes:
      - ./nginx-port/html/:/usr/share/nginx/html/
      - ./nginx-port/configuration/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      port-network:
        ipv4_address: 172.35.0.3

  php:
    container_name: php-port
    build: ./php-port
    volumes:
      - ./php-port/html/:/var/www/html/
      - ./php-port/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      port-network:
        ipv4_address: 172.35.0.2

networks:
  port-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/16
