services:
  web:
    build:
      context: ./nginx-dockerfile
      dockerfile: Dockerfile
    ports:
      - '8090:80'
    volumes:
      - ./code:/code
      - ./site/default.conf:/etc/nginx/conf.d/default.conf
      - phpsocket:/run/php/php-fpm.sock
    networks:
      - code-network

  php:
    build:
      context: ./php-dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
      - ./www-conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - phpsocket:/run/php/php-fpm.sock
    networks:
      - code-network

volumes:
  phpsocket: null

networks:
  code-network:
    driver: bridge
