---
- name: Create VM on GCP
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - gcp_docker
- name: Configure VM with Docker and Nginx
  hosts: launched
  become: yes
  roles:
    - configure_docker
